name: README build

on:
  push:
    branches:
      - main
  schedule:
    - cron: "30 18 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Get Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Configure pip cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/cache/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install -r cache/requirements.txt || echo "Warning: Some packages may be missing"

      - name: Update image files
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          USER_NAME: ${{ secrets.USER_NAME }}
        run: python today.py

      - name: Check for changes
        run: |
          git add .
          if git diff --cached --exit-code; then
            echo "No changes to commit"
            exit 0
          fi

      - name: Configure Git
        run: |
          git config --global user.email "github-actions-bot@ugly-custard.github.io"
          git config --global user.name "ugly-custard/GitHub-Actions-Bot"

      - name: Commit and push changes
        run: |
          git commit -m "Updated stats" -a || echo "Nothing to commit"
          git push origin main || echo "Push failed - maybe no changes?"
